### ISSUE TITLE
CA MARCHE PLUS

### ISSUE THREAD

**Issue by YouLeGamer** [caca63/mycode#2]
Oui rebonjour c'est moi le client chiant à l'accueil du magasin qui vient pour vous dire **qu'il a perdu son enfant dans un rayon DU SUPERMARCHÉÉÉ EN PARTANT CHERCHER LE LAIIIIIIIIIIIIIT** (pardon)

donc
Le jeu marche plus depuis que mon issue est réglée. Le "Choose a pseudo" se display normalement, mais dès que j'essaye de taper quoi que ce soit... POUF ça crash avec un code erreur que je joins plus loin. Parfois ça ne donne même pas de code erreur, juste python crash lamentablement comme moi quand y'a un truc dégueu à la cantine.

**Comment by YouLeGamer** [comment]
Code erreur avec Programiz (python s'est décidé à juste crash finalement):
![image](https://user-images.githubusercontent.com/125671158/223861279-dbcf11bb-5eab-41d0-990a-fecc3b5f822f.png)

**Comment by caca63** [comment]
CA MARCHE CB T CONTENT ??????EFBEZGJEZF GH?FJEZF.

**Comment by caca63** [comment]
Cordialement, food.
